CREATE TABLE public.COMPRA (ID_COMPRA serial PRIMARY KEY, 
							ID_VENDEDOR int NOT NULL,
							FOREIGN KEY (ID_VENDEDOR) REFERENCES public.VENDEDOR (ID_VENDEDOR),
							ID_CLIENTE int NOT NULL,
							FOREIGN KEY (ID_CLIENTE) REFERENCES public.CLIENTE (ID_CLIENTE),
							VALOR_COMPRA numeric,
							ID_TIPO_COMPRA int NOT NULL,
							FOREIGN KEY (ID_TIPO_COMPRA) REFERENCES public.TIPO_COMPRA (ID_TIPO_COMPRA)
						   );
										 
select * from public.COMPRA

-- DROP TABLE PUBLIC.COMPRA