CREATE TABLE public.IMOVEL (ID_IMOVEL serial PRIMARY KEY, 
							ID_ENDERECO_IMOVEL int NOT NULL,
							FOREIGN KEY (ID_ENDERECO_IMOVEL) REFERENCES public.ENDERECO_IMOVEL (ID_ENDERECO_IMOVEL),
							ID_PROP int NOT NULL,
							FOREIGN KEY (ID_PROP) REFERENCES public.PROPRIETARIO_IMOVEL (ID_PROP),
							ID_VENDEDOR int NOT NULL,
							FOREIGN KEY (ID_VENDEDOR) REFERENCES public.VENDEDOR (ID_VENDEDOR),
							ID_TIPO_IMOVEL int NOT NULL,
							FOREIGN KEY (ID_TIPO_IMOVEL) REFERENCES public.TIPO_IMOVEL (ID_TIPO_IMOVEL),
							ID_COMPRA int NOT NULL,
							FOREIGN KEY (ID_COMPRA) REFERENCES public.COMPRA (ID_COMPRA)
						   );
										 
select * from public.IMOVEL

-- DROP TABLE PUBLIC.IMOVEL