CREATE TABLE public.TIPO_COMPRA (ID_TIPO_COMPRA serial PRIMARY KEY, 
								 VISTA boolean,
								 ID_FINANCIAMENTO int NOT NULL,
							     FOREIGN KEY (ID_FINANCIAMENTO) REFERENCES public.FINANCIAMENTO_COMPRA (ID_FINANCIAMENTO));
										 
select * from public.TIPO_COMPRA

-- DROP TABLE PUBLIC.TIPO_COMPRA